# Site settings
title: uniapp开源社区
email: 191010848@qq.com
description: > # this means to ignore newlines until "baseurl:"
  uniapp开源社区主要分享uniapp模板、组件、js sdk、原生sdk，欢迎大家勇于投稿，分享作品。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uniapp.red" # the base hostname & protocol for your site
twitter_username: 无
github_username:  无
facebook_username: 无
google_play: 'GDGX'
google_plus_com: '109485346959707049693'  # Community link
google_plus_per: '+GDGManagua'  #Personal link
facebook_app_id: 12345

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

disqus: true
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
